const galleryItems = Array.from({ length: 35 }, (_, index) => {
  const position = index + 1

  return {
    id: `memory-${position}`,
    order: position,
    sourceFile: `${position}.jpg`,
    date: null,
    caption: `Khoảnh khắc ${position} — nội dung sẽ được bổ sung sau.`,
    note: null,
  }
})

export const birthdayContent = {
  recipient: {
    fullName: 'Chu Thị Hiền Lương',
    displayName: 'Hiền Lương',
    birthDate: '2005-09-17',
    celebrationDate: '2026-09-17',
    turningAge: 21,
  },
  relationship: {
    startDate: '2023-09-01',
    featuredMilestoneDate: '2026-09-16',
    featuredDayCount: 1111,
    birthdayDayCount: 1112,
    yearsTogether: 3,
    motif: 'Always only you',
  },
  experience: {
    title: 'Ebe Hien Luong',
    introLockDurationMs: 10_000,
    introCompleteHoldMs: 3_000,
    introFadeToBlackDurationMs: 3_000,
    heroFadeInDurationMs: 2_000,
    allowIntroSkip: false,
    defaultAudioMuted: false,
  },
  emailLanding: {
    senderLabel: 'SCAM ACHIEVED',
    recordCode: '1U1O1Y-YL1NO',
    callToAction: 'Mở dữ liệu dành cho tôi',
    headline: 'Đây là link scammmm đó nghen',
    description: 'Hồ sơ đã được mã hóa và gắn với duy nhất một người nhận. Hãy xác nhận để mở nội dung đang chờ bên trong.',
    footnote: 'Giữ nguyên màn hình trong quá trình hệ thống xác nhận quyền truy cập.',
  },
  intro: {
    windowTitle: 'root@only-you: ~/secure-record',
    warning: 'UNAUTHORIZED ACCESS SEQUENCE DETECTED',
    headline: 'SYSTEM BREACH',
    headlineLines: ['SYSTEM BREACH'],
    progressLabel: 'Injecting celebration protocol',
    completeLabel: 'Payload synchronized',
    lockMessage: 'SYSTEM INPUT LOCKED · DO NOT CLOSE THIS WINDOW',
    terminalLines: [
      '[SYS] Initializing encrypted tunnel…',
      '[NET] Remote handshake accepted / latency 17ms',
      '[AUTH] Identity signature located: H.LUONG',
      '[AUTH] Permission layer bypassed',
      '[DATA] Mounting private memory archive…',
      '[SCAN] 35 visual records indexed',
      '[CORE] ONLY-YOU-1111 protocol injected',
      '[EXEC] Preparing final payload…',
    ],
  },
  sections: [
    {
      id: 'intro',
      shortLabel: 'Intro',
      sceneModule: 'IntroHack',
      icon: '⌁',
      eyebrow: 'Section 0 · Access sequence',
      title: 'Đang xác nhận quyền truy cập…',
      description: 'Landing và intro hacker khóa 10 giây sẽ được triển khai ở các mốc 1.5–1.8.',
      phaseNote: 'Shell sẵn sàng · Chưa kích hoạt timing hoặc hiệu ứng hacker',
    },
    {
      id: 'hero',
      shortLabel: 'Hero',
      sceneModule: 'HeroScene',
      icon: '✦',
      eyebrow: 'Section 1 · The reveal',
      title: 'Chúc mừng sinh nhật {recipient}',
      description: 'Một bầu trời hồng tím, mascot tiên nguyên bản và hành trình chỉ dành cho một người.',
      heroCopy: {
        tagLabel: 'Ngày của em bé',
        tagDateLabel: '17.9.2026',
        headline: 'Happy Birthday Ngiu Hiền Lương xinh đẹp của a',
        timelineLead: '1.111 ngày được bên em bé',
        loveLine: 'I love u so much and be always only you.',
      },
      phaseNote: 'R3.1–R3.9 · Hero copy, mascot và nhịp phép thuật',
    },
    {
      id: 'cake',
      shortLabel: 'Cake',
      sceneModule: 'CakeScene',
      icon: '◌',
      eyebrow: 'Section 2 · Make a wish',
      title: 'Một điều ước nhỏ',
      description: 'Bánh sinh nhật, nến phép thuật và tương tác thổi nến sẽ xuất hiện tại đây.',
      cakeCopy: {
        completeMessage: 'Năm ngọn nến đã tắt. Điều ước đang bay lên cùng phép màu ✦',
        resetButtonHint: 'Thắp lại nến và bắt đầu từ điều ước',
        resetButtonLabel: 'Thử lại nghi thức',
        resetWaitingHint: 'Chờ ngôi sao bay xong một chút nhé',
        extinguishingMessage: 'Gió phép thuật đang đi qua · còn {count} ngọn nến',
        idleMessage: 'Điều ước đã sẵn sàng. Hít một hơi thật sâu rồi thổi tắt năm ngọn nến.',
        awaitingWishMessage: 'Hãy viết và giữ lại điều ước bí mật trước khi thổi nến.',
        awaitingWishHint: 'Hoàn tất điều ước ở phía trên để mở khóa',
        micButtonLabel: 'Thổi nến bằng microphone',
        micCalibratingHint: 'Hãy giữ yên lặng trong giây lát để đo tiếng nền',
        micCalibratingLabel: 'Đang hiệu chỉnh độ nhạy…',
        micListeningHint: 'Thổi một hơi dài vào microphone',
        micListeningLabel: 'Microphone đang lắng nghe',
        micPermissionHint: 'Chỉ lắng nghe tại thiết bị, không ghi âm',
        micRequestingLabel: 'Đang xin quyền microphone…',
        micUnavailableLabel: 'Không thể dùng microphone',
        micRetryHint: 'Bạn có thể cấp lại quyền hoặc tắt từng nến trực tiếp',
        micRetryLabel: 'Thử lại microphone',
        micFallbackInteractionHint: 'Chạm từng ngọn lửa, hoặc dùng Tab rồi Enter hay phím cách để tắt nến.',
        candleGroupLabel: 'Năm ngọn nến sinh nhật, còn {count} ngọn đang sáng',
        candleLitLabel: 'Nến số {number} đang sáng. Kích hoạt để tắt nến.',
        candleOutLabel: 'Nến số {number} đã tắt.',
        micFallback: {
          busy: 'Microphone đang được ứng dụng khác sử dụng.',
          denied: 'Quyền microphone đã bị từ chối.',
          'not-found': 'Không tìm thấy microphone trên thiết bị.',
          security: 'Trang cần chạy qua HTTPS hoặc localhost để dùng microphone.',
          timeout: 'Đã chờ quyền microphone quá lâu.',
          unknown: 'Microphone gặp lỗi ngoài dự kiến.',
          unsupported: 'Trình duyệt này không hỗ trợ microphone.',
        },
        wishForm: {
          charactersRemainingLabel: 'ký tự còn lại',
          draftMessage: 'Lời ước chỉ được lưu khi bạn nhấn gửi.',
          hint: 'Điều ước được lưu riêng trên thiết bị này.',
          idleMessage: 'Viết một điều thật lòng rồi gửi nó lên bầu trời nhé.',
          label: 'Điều ước bí mật của bạn',
          maxLength: 180,
          placeholder: 'Mình ước rằng…',
          readyButtonLabel: 'Điều ước đã được giữ',
          readyMessage: 'Điều ước đã sẵn sàng. Giờ hãy thổi nến nhé ✦',
          sentButtonLabel: 'Đã hóa thành ngôi sao',
          sentMessage: 'Điều ước đã được cất giữ và bay lên thành một ngôi sao ✦',
          sentUnsavedMessage: 'Ngôi sao đã bay lên, nhưng trình duyệt không cho phép lưu điều ước.',
          storageKey: 'twinkle-birthday:wish',
          submitLabel: 'Gửi điều ước',
        },
      },
      phaseNote: 'Phase 3 hoàn tất · Nghi thức, responsive MacBook, quyền mic và hiệu năng đã được nghiệm thu',
    },
    {
      id: 'letter',
      shortLabel: 'Letter',
      sceneModule: 'LetterScene',
      icon: '♡',
      eyebrow: 'Section 3 · A letter for you',
      title: 'Những điều muốn gửi đến em',
      description: 'Placeholder đủ dài để ước lượng phong bì, giấy viết và nhịp typing animation.',
      letterCopy: {
        closeHint: 'Đóng lại để xem nghi thức thêm một lần nữa',
        closeLabel: 'Gấp lá thư lại',
        closedStatus: 'Phong bì đang chờ em mở.',
        closingStatus: 'Lá thư đang được gấp lại…',
        emptyMessage: 'Lá thư đang chờ những lời thật lòng được viết vào.',
        openHint: 'Có một điều dịu dàng đang chờ bên trong',
        openLabel: 'Mở lá thư',
        openStatus: 'Lá thư đã mở. Mình cùng đọc nhé ✦',
        openingStatus: 'Con dấu phép thuật đang mở…',
        placeholderNotice: 'Bản nháp để kiểm tra bố cục · Nội dung chính thức sẽ được thay trong config',
        previewLabel: 'Nội dung lá thư sinh nhật',
        salutation: 'Gửi em,',
        signOff: 'Thương em,',
        signature: 'Người luôn chọn em',
      },
      placeholderSentences: [
        'Hello em bé, năm nay a không biết làm gì thật sự bất ngờ cho ebe hết nên là a ngồi làm cái này hehe. Mặc dù nó chưa hoàn hảo như suy nghĩ của a lắm, nhma hy vọng embe sẽ thích nó .......',
        'Mong những gì embe ước nguyện sẽ trở thành điều hướng ebe đến một tương lai rực sáng hơn.  ',
        'Năm nay là một năm quan trọng của tụi mình, bước đà cho việc cố gắng và phát triển sau này. Nên eiu càng phải cố gắng hơn nha. Tính ra, không biết năm nay a có làm eiu buồn gì nhìu hong ta, nếu có thì eiu đừng để tâm nhó, a iu ebe nhìu lắm, và sẽ cố gắng mang lại yêu thương, hạnh phúc cho eiu',
        'Cùng nhau quyết tâm, phấn đấu hơn nữa nha eiu.',
        'Lời hẹn ước tủi hăm nhăm'
      ],
      phaseNote: 'Phase 4 hoàn tất · Đang dùng 10 câu placeholder, nội dung thật sẽ thay trong config',
    },
    {
      id: 'gallery',
      shortLabel: 'Gallery',
      sceneModule: 'GalleryScene',
      icon: '▧',
      eyebrow: 'Section 4 · Our memories',
      title: '35 khoảnh khắc của chúng mình',
      description: 'Ảnh đã được đánh thứ tự theo hành trình từ lúc quen nhau đến hiện tại.',
      items: galleryItems,
      phaseNote: 'Metadata placeholder đã sẵn sàng · Texture pipeline thuộc Phase 5',
    },
    {
      id: 'outro',
      shortLabel: 'Outro',
      sceneModule: 'OutroScene',
      icon: '∞',
      eyebrow: 'Section 5 · Only you',
      title: 'Và phép màu vẫn còn tiếp tục',
      description: 'Mascot, pháo hoa sao và lời nhắn cuối sẽ khép lại trải nghiệm.',
      phaseNote: 'Shell sẵn sàng · Animation và âm thanh thuộc Phase 6',
    },
  ],
}
