import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import '@fontsource/baloo-2/latin-700.css'
import '@fontsource/baloo-2/vietnamese-700.css'
import '@fontsource/baloo-2/latin-800.css'
import '@fontsource/baloo-2/vietnamese-800.css'
import '@fontsource/quicksand/latin-400.css'
import '@fontsource/quicksand/vietnamese-400.css'
import '@fontsource/quicksand/latin-500.css'
import '@fontsource/quicksand/vietnamese-500.css'
import '@fontsource/quicksand/latin-600.css'
import '@fontsource/quicksand/vietnamese-600.css'
import '@fontsource/quicksand/latin-700.css'
import '@fontsource/quicksand/vietnamese-700.css'
import '@fontsource/caveat/latin-500.css'
import '@fontsource/caveat/latin-ext-500.css'
import '@fontsource/caveat/latin-600.css'
import '@fontsource/caveat/latin-ext-600.css'
import '@fontsource/caveat/latin-700.css'
import '@fontsource/caveat/latin-ext-700.css'
import '@fontsource/dancing-script/latin-600.css'
import '@fontsource/dancing-script/vietnamese-600.css'
import '@fontsource/dancing-script/latin-700.css'
import '@fontsource/dancing-script/vietnamese-700.css'
import App from './App.jsx'
import './styles/global.css'
import './styles/hero-r37.css'
import './styles/hero-r38.css'
import './styles/cake-r41.css'
import './styles/cake-r44.css'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
